version: 2.1
orbs:
    docker: circleci/docker@1.0.1
    kube-orb: circleci/kubernetes@0.11.0
    go: circleci/go@1.1.1

parameters:
  ci_service_controller_image:
    default: quay.io/nicob87/service-controller:${CIRCLE_SHA1}
    type: string

  ci_site_controller_image:
    default: quay.io/nicob87/site-controller:${CIRCLE_SHA1}
    type: string

  ci_test_image:
    default: quay.io/nicob87/skupper-tests:${CIRCLE_SHA1}
    type: string

executors:
  local_cluster_test_executor:
    machine:
      image: circleci/classic:latest

commands:
  minikube-install:
    description: Installs the minikube executable onto the system.
    steps:
      - run:
          command: >-
            curl -Lo minikube
            https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64 && 
            chmod +x minikube && sudo
            mv minikube /usr/local/bin/
          name: Install Minikube Executable

  minikube-start:
    description: Starts the minikube service.
    steps:
      - run:
          command: >-
            minikube start --vm-driver=docker --cpus 2 --memory 2048
          name: Start Minikube Cluster

  minikube-start-load-balancer:
    description: Starts the minikube tunnel
    steps:
      - run:
          command: minikube tunnel
          name: Start Minikube Tunnel
          background: true

  prepare_for_local_cluster_tests:
    description: install right versions of go, docker, kubectl, and also build
    steps:
      - run:
          name: Export environment variables persistent in execution shell
          command: |
            echo 'export KUBECONFIG=/home/circleci/.kube/config' >> $BASH_ENV
            echo 'export GOROOT=/usr/local/go' >> $BASH_ENV
            echo 'export GOPATH=$HOME/go' >> $BASH_ENV
            echo 'export PATH=$GOPATH/bin:$GOROOT/bin:$PATH' >> $BASH_ENV
            echo 'export SKUPPER_SERVICE_CONTROLLER_IMAGE=<< pipeline.parameters.ci_service_controller_image >>' >> $BASH_ENV
            echo 'export SKUPPER_SITE_CONTROLLER_IMAGE=<< pipeline.parameters.ci_site_controller_image >>' >> $BASH_ENV
            echo 'export TEST_IMAGE=<< pipeline.parameters.ci_test_image >>' >> $BASH_ENV
            source $BASH_ENV
      - checkout
      - run:
          name: cleanup previous go installation
          command: sudo rm -rf /usr/local/go
      - docker/install-docker
      - go/install
      - kube-orb/install-kubectl
      - run: make

  run_cluster_tests:
    description: run all e2e tests inside the current KUBECONFIG configured cluster
    parameters:
      args:
        default: ""
        type: string
    steps:
      - run:
          name: Run Integration Tests
          command: go test -tags=integration -v ./test/integration/...
      - run:
          name: Run client tests in real cluster
          command: go test -v -count=1 ./client -use-cluster

  compile_go_program:
    description: Compile specified platform.
    parameters:
      platform:
        type: string
      goos:
        type: string
      goarch:
        type: string
      exesuffix:
        default: ""
        type: string
    steps:
      - run:
          name: Building << parameters.platform >>
          command: >-
            VERSION="${CIRCLE_TAG:-ci-${CIRCLE_BUILD_NUM}}";
            GOOS=<< parameters.goos >>
            GOARCH=<< parameters.goarch >>
            go build -ldflags "-X main.version=${VERSION}"
            -o dist/<< parameters.platform >>/skupper<< parameters.exesuffix >>
            ./cmd/skupper

yaml-templates:
  branch_filters: &run_for_all_branches_and_v_prefixed_tags
    filters:
      tags:
        only: /^v.*/

  release_filters: &run_for_v_prefixed_tags
    filters:
      branches:
        ignore: /.*/
      tags:
        only: /^v.*/

  release_requires: &release_requires
    requires:
      - build-all
      - test
      - minikube_local_cluster_tests

  minikube_local_cluster_tests: &minikube_local_cluster_tests
       <<: *run_for_all_branches_and_v_prefixed_tags
       pre-steps:
         - prepare_for_local_cluster_tests
       requires:
         - test

workflows:
  version: 2.1
  build-workflow:
    jobs:
      - build-all:
          <<: *run_for_all_branches_and_v_prefixed_tags
      - test:
          <<: *run_for_all_branches_and_v_prefixed_tags

      - m0:
          <<: *minikube_local_cluster_tests
      - m1:
          <<: *minikube_local_cluster_tests
      - m2:
          <<: *minikube_local_cluster_tests
      #- m3:
          #<<: *minikube_local_cluster_tests
      #- m4:
          #<<: *minikube_local_cluster_tests
      #- m5:
          #<<: *minikube_local_cluster_tests
      #- m6:
          #<<: *minikube_local_cluster_tests
      #- m7:
          #<<: *minikube_local_cluster_tests
      #- m8:
          #<<: *minikube_local_cluster_tests
      #- m9:
          #<<: *minikube_local_cluster_tests
      #- m10:
          #<<: *minikube_local_cluster_tests
      #- m11:
          #<<: *minikube_local_cluster_tests
      #- m12:
          #<<: *minikube_local_cluster_tests
      #- m13:
          #<<: *minikube_local_cluster_tests
      #- m14:
          #<<: *minikube_local_cluster_tests
      #- m15:
          #<<: *minikube_local_cluster_tests
      #- m16:
          #<<: *minikube_local_cluster_tests
      #- m17:
          #<<: *minikube_local_cluster_tests
      #- m18:
          #<<: *minikube_local_cluster_tests
      #- m19:
          #<<: *minikube_local_cluster_tests
      #- m20:
          #<<: *minikube_local_cluster_tests
      #- m21:
          #<<: *minikube_local_cluster_tests
      #- m22:
          #<<: *minikube_local_cluster_tests
      #- m23:
          #<<: *minikube_local_cluster_tests
      #- m24:
          #<<: *minikube_local_cluster_tests
      #- m25:
          #<<: *minikube_local_cluster_tests
      #- m26:
          #<<: *minikube_local_cluster_tests
      #- m27:
          #<<: *minikube_local_cluster_tests
      #- m28:
          #<<: *minikube_local_cluster_tests
      #- m29:
          #<<: *minikube_local_cluster_tests
      #- m210:
          #<<: *minikube_local_cluster_tests
      #- m211:
          #<<: *minikube_local_cluster_tests
      #- m212:
          #<<: *minikube_local_cluster_tests
      #- m213:
          #<<: *minikube_local_cluster_tests
      #- m214:
          #<<: *minikube_local_cluster_tests
      #- m215:
          #<<: *minikube_local_cluster_tests
      #- m216:
          #<<: *minikube_local_cluster_tests
      #- m217:
          #<<: *minikube_local_cluster_tests
      #- m218:
          #<<: *minikube_local_cluster_tests
      #- m219:
          #<<: *minikube_local_cluster_tests
      #- m30:
          #<<: *minikube_local_cluster_tests
      #- m31:
          #<<: *minikube_local_cluster_tests
      #- m32:
          #<<: *minikube_local_cluster_tests
      #- m33:
          #<<: *minikube_local_cluster_tests
      #- m34:
          #<<: *minikube_local_cluster_tests
      #- m35:
          #<<: *minikube_local_cluster_tests
      #- m36:
          #<<: *minikube_local_cluster_tests
      #- m37:
          #<<: *minikube_local_cluster_tests
      #- m38:
          #<<: *minikube_local_cluster_tests
      #- m39:
          #<<: *minikube_local_cluster_tests
      #- m310:
          #<<: *minikube_local_cluster_tests
      #- m311:
          #<<: *minikube_local_cluster_tests
      #- m312:
          #<<: *minikube_local_cluster_tests
      #- m313:
          #<<: *minikube_local_cluster_tests
      #- m314:
          #<<: *minikube_local_cluster_tests
      #- m315:
          #<<: *minikube_local_cluster_tests
      #- m316:
          #<<: *minikube_local_cluster_tests
      #- m317:
          #<<: *minikube_local_cluster_tests
      #- m318:
          #<<: *minikube_local_cluster_tests
      #- m319:
          #<<: *minikube_local_cluster_tests
      #- m320:
          #<<: *minikube_local_cluster_tests
      #- m321:
          #<<: *minikube_local_cluster_tests
      #- m322:
          #<<: *minikube_local_cluster_tests
      #- m323:
          #<<: *minikube_local_cluster_tests
      #- m324:
          #<<: *minikube_local_cluster_tests
      #- m325:
          #<<: *minikube_local_cluster_tests
      #- m326:
          #<<: *minikube_local_cluster_tests
      #- m327:
          #<<: *minikube_local_cluster_tests
      #- m328:
          #<<: *minikube_local_cluster_tests
      #- m329:
          #<<: *minikube_local_cluster_tests
      #- m3210:
          #<<: *minikube_local_cluster_tests
      #- m3211:
          #<<: *minikube_local_cluster_tests
      #- m3212:
          #<<: *minikube_local_cluster_tests
      #- m3213:
          #<<: *minikube_local_cluster_tests
      #- m3214:
          #<<: *minikube_local_cluster_tests
      #- m3215:
          #<<: *minikube_local_cluster_tests
      #- m3216:
          #<<: *minikube_local_cluster_tests
      #- m3217:
          #<<: *minikube_local_cluster_tests
      #- m3218:
          #<<: *minikube_local_cluster_tests
      #- m3219:
          #<<: *minikube_local_cluster_tests
      #- m40:
          #<<: *minikube_local_cluster_tests
      #- m41:
          #<<: *minikube_local_cluster_tests
      #- m42:
          #<<: *minikube_local_cluster_tests
      #- m43:
          #<<: *minikube_local_cluster_tests
      #- m44:
          #<<: *minikube_local_cluster_tests
      #- m45:
          #<<: *minikube_local_cluster_tests
      #- m46:
          #<<: *minikube_local_cluster_tests
      #- m47:
          #<<: *minikube_local_cluster_tests
      #- m48:
          #<<: *minikube_local_cluster_tests
      #- m49:
          #<<: *minikube_local_cluster_tests
      #- m410:
          #<<: *minikube_local_cluster_tests
      #- m411:
          #<<: *minikube_local_cluster_tests
      #- m412:
          #<<: *minikube_local_cluster_tests
      #- m413:
          #<<: *minikube_local_cluster_tests
      #- m414:
          #<<: *minikube_local_cluster_tests
      #- m415:
          #<<: *minikube_local_cluster_tests
      #- m416:
          #<<: *minikube_local_cluster_tests
      #- m417:
          #<<: *minikube_local_cluster_tests
      #- m418:
          #<<: *minikube_local_cluster_tests
      #- m419:
          #<<: *minikube_local_cluster_tests


jobs:
  test:
    executor:
      name: go/default
      tag: "1.13"
    steps:
      - checkout
      - run:
          name: "Enforce Go Formatted Code"
          command: >
              if [ `make format -s | wc -l` -ne 0 ]; then
                git --no-pager diff
                echo "Bad formatting! execute \"\$make format\" locally and push again!"
                exit 1
              fi

      - run:
          name: Export environment variables persistent in execution shell
          command: |
            echo 'export SERVICE_CONTROLLER_IMAGE=<< pipeline.parameters.ci_service_controller_image >>' >> $BASH_ENV
            echo 'export SITE_CONTROLLER_IMAGE=<< pipeline.parameters.ci_site_controller_image >>' >> $BASH_ENV
            echo 'export TEST_IMAGE=<< pipeline.parameters.ci_test_image >>' >> $BASH_ENV
            source $BASH_ENV
      - setup_remote_docker
      - go/mod-download-cached
      - run: make
      - run: docker login quay.io -u ${DOCKER_LOGIN} -p ${DOCKER_PASSWORD}
      - run: make -e docker-build
      - run: make -e docker-push
      - run: make package
      - run: make clean
      - go/test

  remove_from_registry:
    executor:
      name: go/default
      tag: "1.13"
    steps:
      - setup_remote_docker
      - run: docker login quay.io -u ${DOCKER_LOGIN} -p ${DOCKER_PASSWORD}
      - run: go get github.com/genuinetools/reg
      - run: reg rm << pipeline.parameters.ci_service_controller_image >>
      - run: reg rm << pipeline.parameters.ci_site_controller_image >>
      - run: reg rm << pipeline.parameters.ci_test_image >>

  build-all:
    executor:
      name: go/default
      tag: "1.13"
    steps:
      - checkout
      - go/mod-download-cached

      - compile_go_program:
          goos: linux
          goarch: amd64
          platform: linux-amd64

      - compile_go_program:
          goos: linux
          goarch: "386"
          platform: linux-i386

      - compile_go_program:
          goos: windows
          goarch: "386"
          platform: windows-i386
          exesuffix: ".exe"

      - compile_go_program:
          goos: windows
          goarch: amd64
          platform: windows-amd64
          exesuffix: ".exe"

      - compile_go_program:
          goos: darwin
          goarch: "386"
          platform: mac-i386

      - compile_go_program:
          goos: darwin
          goarch: amd64
          platform: mac-amd64

      - compile_go_program:
          goos: linux
          goarch: arm
          platform: linux-arm32

      - compile_go_program:
          goos: linux
          goarch: arm64
          platform: linux-arm64

      - persist_to_workspace:
          root: .
          paths:
              - dist

  minikube_local_cluster_tests:
    executor: local_cluster_test_executor
    steps:
      - run: echo "skupper_image = ${SKUPPER_SERVICE_CONTROLLER_IMAGE}"
      - minikube-install
      - minikube-start
      - minikube-start-load-balancer
      - run: kubectl cluster-info
      - run_cluster_tests

  publish-github-release-artifacts:
    docker:
      - image: cibuilds/github:0.10
    steps:
      - attach_workspace:
          at: .
      - run:
          name: "Create a Draft Release on GitHub"
          command: |
            VERSION="${CIRCLE_TAG}"
            BASEDIR=`pwd`
            mkdir "${BASEDIR}/archives"
            for p in `ls dist` ; do
              cd "$BASEDIR/dist/$p"
              if [[ $p == windows* ]] ; then
                zip -q "${BASEDIR}/archives/skupper-cli-${VERSION}-$p.zip" *
              else
                tar -zcf "${BASEDIR}/archives/skupper-cli-${VERSION}-$p.tgz" *
              fi
            done
            cd ${BASEDIR}
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -replace -prerelease -draft ${VERSION} "${BASEDIR}/archives"

  publish-github-release-images:
    executor:
      name: go/default
      tag: "1.13"
    steps:
      - checkout
      - setup_remote_docker
      - run: docker login quay.io -u ${DOCKER_LOGIN} -p ${DOCKER_PASSWORD}
      - run:
          name:
          command: |
            echo 'export SERVICE_CONTROLLER_IMAGE=quay.io/nicob87/service-controller:${CIRCLE_TAG}' >> $BASH_ENV
            echo 'export SITE_CONTROLLER_IMAGE=quay.io/nicob87/site-controller:${CIRCLE_TAG}' >> $BASH_ENV
            source $BASH_ENV
            make -e docker-build
            make -e docker-push
